name: news_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  intl: ^0.18.1
  url_launcher: ^6.1.11
  lottie: ^2.3.2
  build_runner: ^2.3.3 #used to generate codes for state management
  freezed: ^2.3.2 #code generation package
  hooks_riverpod: ^2.3.4 #state management package
  flutter_riverpod: ^2.3.4 #state management package
  logger: ^1.3.0 #retrieving log reports
  flutter_dotenv: ^5.0.2 #used for storing api endpoints and keys
  dio: ^5.1.2 #used to make individual HTTP requests

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - .env
     - assets/images/
     - assets/images/screenshot/
     - assets/json/
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Regular.ttf
         - asset: assets/fonts/Inter-Black.ttf
         - asset: assets/fonts/Inter-Bold.ttf
         - asset: assets/fonts/Inter-SemiBold.ttf
         - asset: assets/fonts/Inter-Light.ttf
         - asset: assets/fonts/Inter-Medium.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
